#!/bin/bash
# Debian Sway/Wayland Rice Setup Script
# Automated installation and configuration
# Run as regular user (will prompt for sudo password)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== Debian Sway/Wayland Rice Setup ===${NC}"
echo

# Function to print colored messages
print_step() {
    echo -e "${BLUE}>>> $1${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

# Check if running as root
if [ "$EUID" -eq 0 ]; then 
    print_error "Please run as regular user, not root"
    exit 1
fi

# Backup existing configs
backup_configs() {
    print_step "Backing up existing configs..."
    
    BACKUP_DIR="$HOME/.config-backup-$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$BACKUP_DIR"
    
    [ -d "$HOME/.config/sway" ] && cp -r "$HOME/.config/sway" "$BACKUP_DIR/"
    [ -d "$HOME/.config/waybar" ] && cp -r "$HOME/.config/waybar" "$BACKUP_DIR/"
    [ -d "$HOME/.config/wofi" ] && cp -r "$HOME/.config/wofi" "$BACKUP_DIR/"
    [ -d "$HOME/.config/swaync" ] && cp -r "$HOME/.config/swaync" "$BACKUP_DIR/"
    
    if [ -d "$BACKUP_DIR/sway" ] || [ -d "$BACKUP_DIR/waybar" ]; then
        print_success "Backed up to $BACKUP_DIR"
    else
        print_warning "No existing configs to backup"
    fi
}

# Update system
print_step "Updating system..."
sudo apt update
sudo apt upgrade -y
print_success "System updated"

# Install core packages
print_step "Installing Sway and core tools..."
sudo apt install -y \
    sway waybar wofi foot swaylock swayidle wlogout swaybg \
    grim slurp sway-notification-center \
    brightnessctl playerctl pavucontrol \
    network-manager-gnome blueman \
    wl-clipboard jq imagemagick \
    xwayland psmisc \
    nemo
print_success "Core packages installed"

# Optional: Remove Thunar
read -p "Remove Thunar file manager? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sudo apt remove -y thunar
    sudo apt autoremove -y
    print_success "Thunar removed"
fi

# Create config directories
print_step "Creating config directories..."
mkdir -p ~/.config/sway
mkdir -p ~/.config/waybar
mkdir -p ~/.config/swaync
mkdir -p ~/.config/wofi
mkdir -p ~/.config/foot
mkdir -p ~/Pictures
print_success "Directories created"

# Backup existing configs
backup_configs

# Create Sway config
print_step "Creating Sway config..."
cat > ~/.config/sway/config << 'EOF'
# Steve's Sway Config - Riced Edition
# Auto-generated by setup script

### Variables
set $mod Mod4

# Applications
set $term alacritty
set $menu wofi --show drun

# Directions (vim-style)
set $left h
set $down j
set $up k
set $right l

### Output Configuration (Monitors/Displays)
# Wallpaper (create ~/Pictures/wallpaper.jpg or use solid color)
output * bg #1e1e2e solid_color

### Appearance
font pango:DejaVu Sans Mono 10

# Window borders
default_border pixel 2
default_floating_border pixel 2

# Hide title bars (minimal look)
titlebar_padding 1
titlebar_border_thickness 0

# Gaps
gaps inner 8
gaps outer 4

# Border colors
client.focused          #6dade3 #6dade3 #ffffff #6dade3   #6dade3
client.focused_inactive #333333 #5f676a #ffffff #484e50   #5f676a
client.unfocused        #333333 #222222 #888888 #292d2e   #222222
client.urgent           #2f343a #900000 #ffffff #900000   #900000
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c
client.background       #ffffff

### Idle Configuration
exec swayidle -w \
    timeout 300 'swaylock -f -c 000000' \
    timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
    before-sleep 'swaylock -f -c 000000'

### Input Configuration
input type:touchpad {
    dwt enabled
    tap enabled
    natural_scroll enabled
    middle_emulation enabled
}

input type:keyboard {
    xkb_options caps:escape
}

### Key Bindings

# Terminal
bindsym $mod+Return exec $term

# Kill window
bindsym $mod+Shift+q kill

# Launcher
bindsym $mod+d exec $menu

# Reload config
bindsym $mod+Shift+c reload

# Exit sway
bindsym $mod+Shift+e exec wlogout

# Lock screen
bindsym $mod+backslash exec swaylock -f -c 000000

# Screenshot
bindsym Print exec grim ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png
bindsym $mod+Shift+s exec grim -g "$(slurp)" ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png

# Notification center
bindsym $mod+n exec swaync-client -t -sw

# File manager
bindsym $mod+e exec nemo

# Floating modifier
floating_modifier $mod normal

### Focus Movement (vim-style + arrows)
bindsym $mod+$left focus left
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

### Move Windows
bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

### Workspaces
set $ws1 "1:term"
set $ws2 "2:rider"
set $ws3 "3:git"
set $ws4 "4:web"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# Switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# Move to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

# Workspace assignments
assign [app_id="rider"] $ws2
assign [class="jetbrains-rider"] $ws2
assign [app_id="gitkraken"] $ws3
assign [class="gitkraken"] $ws3
assign [app_id="firefox"] $ws4
assign [class="firefox"] $ws4

### Layout
bindsym $mod+b splith
bindsym $mod+v splitv

bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

bindsym $mod+f fullscreen

bindsym $mod+Shift+space floating toggle
bindsym $mod+space focus mode_toggle

bindsym $mod+a focus parent

### Scratchpad
bindsym $mod+Shift+minus move scratchpad
bindsym $mod+minus scratchpad show

### Resize Mode
mode "resize" {
    bindsym $left resize shrink width 10px
    bindsym $down resize grow height 10px
    bindsym $up resize shrink height 10px
    bindsym $right resize grow width 10px

    bindsym Left resize shrink width 10px
    bindsym Down resize grow height 10px
    bindsym Up resize shrink height 10px
    bindsym Right resize grow width 10px

    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+r mode "resize"

### Media Keys
bindsym --locked XF86AudioRaiseVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindsym --locked XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindsym --locked XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bindsym --locked XF86MonBrightnessUp exec brightnessctl set 10%+
bindsym --locked XF86MonBrightnessDown exec brightnessctl set 10%-

bindsym --locked XF86AudioPlay exec playerctl play-pause
bindsym --locked XF86AudioNext exec playerctl next
bindsym --locked XF86AudioPrev exec playerctl previous

### Status Bar (Waybar)
bar {
    swaybar_command waybar
}

### Autostart Applications
exec swaync
exec nm-applet --indicator
exec blueman-applet

# Include additional configs
include /etc/sway/config.d/*
EOF
print_success "Sway config created"

# Create Waybar config
print_step "Creating Waybar config..."
cat > ~/.config/waybar/config << 'EOF'
{
    "layer": "top",
    "position": "top",
    "height": 30,
    "spacing": 4,
    
    "modules-left": ["sway/workspaces", "sway/mode"],
    "modules-center": ["sway/window"],
    "modules-right": [
        "pulseaudio",
        "network",
        "cpu",
        "memory",
        "disk",
        "battery",
        "clock",
        "tray",
        "custom/notification"
    ],

    "sway/workspaces": {
        "disable-scroll": true,
        "all-outputs": false,
        "format": "{name}"
    },

    "sway/mode": {
        "format": "<span style=\"italic\">{}</span>"
    },

    "sway/window": {
        "max-length": 50
    },

    "tray": {
        "spacing": 10
    },

    "clock": {
        "format": "{:%Y-%m-%d %H:%M}",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>"
    },

    "cpu": {
        "format": "CPU: {usage}%",
        "tooltip": false
    },

    "memory": {
        "format": "RAM: {used:0.1f}G / {total:0.1f}G"
    },

    "disk": {
        "interval": 30,
        "format": "HDD: {free}",
        "path": "/"
    },

    "network": {
        "format-wifi": "WiFi: {essid} ({signalStrength}%)",
        "format-ethernet": "E: {ipaddr} ({bandwidthDownBits})",
        "format-disconnected": "Disconnected",
        "tooltip-format": "{ifname}: {ipaddr}/{cidr}",
        "on-click": "nm-connection-editor"
    },

    "battery": {
        "states": {
            "warning": 30,
            "critical": 15
        },
        "format": "BAT: {capacity}% {icon}",
        "format-charging": "BAT: {capacity}% ",
        "format-plugged": "BAT: {capacity}% ",
        "format-icons": ["", "", "", "", ""]
    },

    "pulseaudio": {
        "format": "VOL: {volume}% {icon}",
        "format-muted": "VOL: MUTE ",
        "format-icons": {
            "headphone": "",
            "hands-free": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", "", ""]
        },
        "on-click": "pavucontrol",
        "scroll-step": 5
    },

    "custom/notification": {
        "tooltip": false,
        "format": "{icon}",
        "format-icons": {
            "notification": "<span foreground='red'><sup></sup></span>",
            "none": "",
            "dnd-notification": "<span foreground='red'><sup></sup></span>",
            "dnd-none": "",
            "inhibited-notification": "<span foreground='red'><sup></sup></span>",
            "inhibited-none": "",
            "dnd-inhibited-notification": "<span foreground='red'><sup></sup></span>",
            "dnd-inhibited-none": ""
        },
        "return-type": "json",
        "exec-if": "which swaync-client",
        "exec": "swaync-client -swb",
        "on-click": "swaync-client -t -sw",
        "on-click-right": "swaync-client -d -sw",
        "escape": true
    }
}
EOF
print_success "Waybar config created"

# Create Waybar style
print_step "Creating Waybar style..."
cat > ~/.config/waybar/style.css << 'EOF'
* {
    border: none;
    border-radius: 0;
    font-family: monospace;
    font-size: 13px;
    min-height: 0;
}

window#waybar {
    background-color: #1e1e2e;
    color: #cdd6f4;
}

#workspaces button {
    padding: 0 10px;
    color: #cdd6f4;
    background-color: transparent;
}

#workspaces button.focused {
    background-color: #6dade3;
    color: #1e1e2e;
}

#workspaces button.urgent {
    background-color: #f38ba8;
    color: #1e1e2e;
}

#mode {
    background-color: #f38ba8;
    color: #1e1e2e;
    padding: 0 10px;
}

#window {
    color: #cdd6f4;
    font-weight: bold;
}

#clock,
#cpu,
#memory,
#disk,
#network,
#battery,
#pulseaudio,
#tray,
#custom-notification {
    padding: 0 10px;
    margin: 0 2px;
    color: #cdd6f4;
}

#cpu {
    color: #89dceb;
}

#memory {
    color: #f9e2af;
}

#disk {
    color: #a6e3a1;
}

#network {
    color: #94e2d5;
}

#network.disconnected {
    color: #f38ba8;
}

#battery {
    color: #fab387;
}

#battery.charging {
    color: #a6e3a1;
}

#battery.warning:not(.charging) {
    color: #f9e2af;
}

#battery.critical:not(.charging) {
    color: #f38ba8;
    animation: blink 1s linear infinite;
}

#pulseaudio {
    color: #b4befe;
}

#pulseaudio.muted {
    color: #f38ba8;
}

@keyframes blink {
    to {
        background-color: #f38ba8;
        color: #1e1e2e;
    }
}

#clock {
    color: #cba6f7;
    font-weight: bold;
}

#tray {
    color: #cdd6f4;
}

#custom-notification {
    color: #89b4fa;
}
EOF
print_success "Waybar style created"

# Create Wofi config
print_step "Creating Wofi config..."
cat > ~/.config/wofi/config << 'EOF'
width=600
height=400
location=center
show=drun
prompt=Search...
filter_rate=100
allow_markup=true
no_actions=true
halign=fill
orientation=vertical
content_halign=fill
insensitive=true
allow_images=true
image_size=40
gtk_dark=true
EOF
print_success "Wofi config created"

# Create Wofi style
print_step "Creating Wofi style..."
cat > ~/.config/wofi/style.css << 'EOF'
window {
    margin: 0px;
    border: 2px solid #6dade3;
    background-color: #1e1e2e;
    border-radius: 8px;
}

#input {
    margin: 5px;
    border: none;
    color: #cdd6f4;
    background-color: #313244;
    border-radius: 4px;
    padding: 8px;
}

#inner-box {
    margin: 5px;
    border: none;
    background-color: #1e1e2e;
}

#outer-box {
    margin: 5px;
    border: none;
    background-color: #1e1e2e;
}

#scroll {
    margin: 0px;
    border: none;
}

#text {
    margin: 5px;
    border: none;
    color: #cdd6f4;
}

#entry:selected {
    background-color: #6dade3;
    color: #1e1e2e;
    border-radius: 4px;
}

#entry:selected #text {
    color: #1e1e2e;
}

#text:selected {
    color: #1e1e2e;
}
EOF
print_success "Wofi style created"

# Set Nemo as default file manager
print_step "Setting Nemo as default file manager..."
xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search 2>/dev/null || true
print_success "Nemo set as default"

# Final messages
echo
print_success "=== Setup Complete! ==="
echo
echo -e "${GREEN}Your Sway/Wayland environment is ready!${NC}"
echo
echo -e "${BLUE}Next steps:${NC}"
echo "1. Log out of your current session"
echo "2. Select 'Sway' from your display manager"
echo "3. Log in and enjoy your riced setup!"
echo
echo -e "${BLUE}Key bindings:${NC}"
echo "  Super+Enter       = Terminal"
echo "  Super+D           = Launcher (wofi)"
echo "  Super+E           = File manager (nemo)"
echo "  Super+N           = Notification center"
echo "  Super+Shift+Q     = Kill window"
echo "  Super+Shift+E     = Exit menu"
echo "  Super+Shift+C     = Reload config"
echo "  Super+\\           = Lock screen"
echo
echo -e "${YELLOW}Optional:${NC}"
echo "- Add wallpaper: cp your-image.jpg ~/Pictures/wallpaper.jpg"
echo "  Then edit ~/.config/sway/config line 19"
echo "- Customize: edit ~/.config/sway/config"
echo "- View backup: $BACKUP_DIR"
echo
print_success "Enjoy your new setup! 🎨"
